version: '3.3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/001.sql
    network_mode: "host"
